name: water_reminder
description: "A new Flutter project for reminding user to drink water."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_launcher_icons: "^0.14.4"

flutter:
  uses-material-design: true

flutter_launcher_icons:
  macos:
    generate: true
    image_path: "assets/app_icon.png"
